[package]
name = "dbip"
version = "0.1.0"
authors = ["hedgar <hedgar2017@gmail.com>"]

[lib]
name = "dbip"

[dependencies]
rusqlite = { version = "0.13.0", features = ["bundled"] }
failure = "0.1.1"
csv = "1.0.0"
